name: Build and release next-actuator

on:
  push:
    branches:
      - main
    paths:
      - 'packages/next-actuator/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/release.yaml'

jobs:
  build:
    name: Build and publish next-actuator
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      id-token: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify provenance
        run: pkg:verify

      - name: Build next-actuator
        run: pnpm pkg:build

      - name: Release next-actuator
        run: pnpm pkg:release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
